### ISSUE TITLE
Missing tags and tests

### ISSUE THREAD

**Issue by jayvdb** [kevinconway/venvctrl#16]
https://github.com/kevinconway/venvctrl/tags doesnt have 0.4.2

PyPI sdist doesnt include tests.

Combined that means there is no (reasonable) way for me to download a 0.4.2 with tests.

And so I cant add tests to https://build.opensuse.org/package/show/home:jayvdb:py-new/python-venvctrl , and so cant submit it to openSUSE.

I would prefer sdists contains tests, but tags are the simpler solution.

**Comment by jayvdb** [comment]
Same problem with https://github.com/kevinconway/rpmvenv/tags

**Comment by kevinconway** [comment]
Yeah, not having the tests package embedded within the normal source tree makes packaging the tests more complicated because of the package name that results (`tests`). I can add some tags, though. Do you only need `venvctrl` and `rpmvenv` or do you also need other transitive dependency that I manage like `confpy` that's used in `rpmvenv`?

**Comment by jayvdb** [comment]
rpmvenv is my packaging goal, so tags for confpy and rpmvenv, etc would be helpful if they are missing.

The extra package "tests" can be excluded from being installed in setup.py using `find_packages(exclude=["tests*"])`, but lots of packages now ignore that step, and it doesnt matter much because most users just fetch the wheels, so you can ensure the wheels are good, and fill the sdist with junk, and only packagers will notice.  And packagers have extra tools at their disposal.  It is normal for setup.py to install `tests` and then I delete the installed `tests` during the build before pressing the RPM.  It is a minor step to add, and quite common.  rpmlint now even has a dedicated check for installed `tests` package, hinting that it needs to be removed.

**Comment by jayvdb** [comment]
confpy is ok, and has been accepted to openSUSE https://build.opensuse.org/package/show/devel:languages:python/python-confpy

So only need tagged tests for venvctrl and rpmvenv.

**Comment by kevinconway** [comment]
OK, I tagged the most recent releases of `venvctrl` and `rpmvenv`.

**Comment by jayvdb** [comment]
Lovely thanks.  I have set up those packages for openSUSE with tests running and passing.  Not sure when I will submit them to the openSUSE collection.
